### ISSUE TITLE
Thank you and questions

### ISSUE THREAD

**Issue by luc-github** [darkspr1te/MKSTFT_Marlin_Touch#15]
Hi first thank you, you bring my MKS back to life ^_^
I have flashed my TFT 32_L V4 with latest BTT firmware which has you PR merged
everything looks fine - I am adding commands for onboard TFT SD and USB and everything is ok out of the box :

```
M115 TFT
FIRMWARE_NAME: .26.1 SOURCE_CODE_URL:https://github.com/luc-github/BIGTREETECH-TouchScreenFirmware/tree/esp3d-support
Cap:TOOL_NUM:1
Cap:EXTRUDER_NUM:1
Cap:FAN_NUM:1
ok
M20 SD:
Begin file list
/MKS.CUR/
End file list
ok
M20 U:
Begin file list
/eclipse/
/Arduino - 1.6.9 -Due 1.6.8/
/GitHub/
/ld5110/
End file list
ok
```
I have noticed FIRMWARE_NAME is incomplete on MKS -
it just give version `.26.1`  instead of full name e.g.: `BIGTREE_TFT35_V3.0.26.1` on BTT TFT

* [Q]  is that a normal ?

Also in process of flashing I have used MKS_32_V1_4 
I had to rename to the `MKS_32_V1_4.26.1.bin` to `mkstft28.bin` and the SD content `TFT28` to `MKS`
I guess this is due to bootloader - 
* [Q] what is MKS_32_V1_4_NOBL for ? I see it means no boot loader but for what usage ?
* [Q]do you plan to update bootloader to allow full update ? drop in the box , without renaming files

I have also an MKS TFT32_L_V2.0 
* [Q]should I change something to flash your porting for this screen ? 

Again thank you for your great work

**Comment by darkspr1te** [comment]
Source for the boot loader (which only handles copying of "firmware" ) is available and the mkstft28.bin requirement can be changed. 
The NOBL version was a development requirement , it would take too long to debug if you had to copy to sd-card each time, this give devs a direct flash/boot option skipping the need for bootloader requirements during debug. 
With the addition of new boards, something BTT didn't really see coming initially, has ment a redesign of the system to differ between boards at many levels, this has introduced bugs for some , I will be pushing hose changes soon, i currently need to finish the bootloader for TFT35 v1 boards first though.
darkspr1te

**Comment by luc-github** [comment]
@darkspr1te thank you again

about MKS TFT32_L_V2.0 : is it supported ? should I do something before flashing ?

**Comment by darkspr1te** [comment]
Short answer is I Don't know, There is only firmware on the makerbase github for the V2.0 , no hardware/firmware that says "v2" , but it must be close in design, what stm chip is it using? if you have a stlink device I would dump the firmware from the device before doing any flash testing. if that cant be done there are ways to dump the flash using code i've published.

**Comment by luc-github** [comment]
Hi thank you again for your help
I took some pictures
![front](https://user-images.githubusercontent.com/8822552/81051940-ea10f180-8ec2-11ea-86f2-53b1159ebfae.jpg)

top is V2 bottom is V4 - 
![both](https://user-images.githubusercontent.com/8822552/81051967-f39a5980-8ec2-11ea-9afe-90af96d800e9.jpg)

![MCU](https://user-images.githubusercontent.com/8822552/81051910-dbc2d580-8ec2-11ea-9c6d-3c854c1997db.jpg)

Looks like layout redesign - the chip is not exactly the same - sorry I am not familiar with STM32 at all so I do not know the difference 
 both are STM32F107 VTC6 but after it is different for what I can see

I do not have  any stlink device only serial 2 USB adapter - I can order a stlink if necessary 

I have tried to flash BTT FW,  but after flashing I got permanent `Updating ....100%.`, so I unplug plug again and got stuck to `booting...` so I revert to MKS FW for the moment.

Let me know how I can help on this - I would be happy to assist

**Comment by Uz45** [comment]
V2 has 4 MB of flash and the output to the screen is different from V4
 [For V2 there is here](https://github.com/Uz45/BIGTREETECH-TouchScreenFirmware/tree/BTT_256_MKSTFT32_V1_V2_V3_V4)

**Comment by luc-github** [comment]
@Uz45 thank you I have just flashed and yes it works ^_^ ESP3D is also working out of the box

@darkspr1te @Uz45 will all this great job will be consolidated and pushed to BTT repository ?

**Comment by Uz45** [comment]
MKS TFT V1 V2 V3 have already been discontinued and their number will be reduced. I don't think it makes sense to add these variants to the main branch.

**Comment by luc-github** [comment]
but that give them a second life like for mine
@Uz45  so you mean when I do PR to BTT I need to do PR to your Github too ?

**Comment by Uz45** [comment]
I track updates in the main BTT branch and when I change the version, I create a new branch while keeping the old one. The old is not always bad :) And I add critical bug fixes immediately.
PS It is not always possible to do this quickly. But I'll do it.

**Comment by luc-github** [comment]
yes newest is not always the best ^_^

ok so I guess issue can be closed @Uz45  I have stared your repo also , so I can follow updates

thank you again
