### ISSUE TITLE
How to send gcode through wifi port?

### ISSUE THREAD

**Issue by tomasbaldi** [darkspr1te/MKSTFT_Marlin_Touch#17]
Hi! I'm using the TX and RX pins to connect to my ESP32, and I wanted to know how to send a gcode.

Thank you!!

**Comment by tomasbaldi** [comment]
Is there a protocol to communicate or just sending through the UART "M115" should it work?

**Comment by tiwanacote** [comment]
It is the same protocol that you use to write to the motherboard, just send an "G01 X10\n". 
If you use the original firmware you have to encode to an specific protocol in which documentation there are several errors
