### ISSUE TITLE
Wifi RX/TX

### ISSUE THREAD

**Issue by luc-github** [darkspr1te/MKSTFT_Marlin_Touch#3]
First nice work even I did not tested yet - which want to do ^_^
Mks use different Serial pins in wifi header depending of which module is connected
Which pins on header do you use for RX/TX ?

I damaged one BTT serial TFT using rx instead of tx so I want to be sure I won't do mistake on MKS :D 

I have MKS TFT 32 V4.0 and another V2.0 I can't wait to try your FW with ESP3D wifi ^_^

**Comment by Uz45** [comment]
MKS TFT 3.2 V4.0 + MKSTFT_Marlin_Touch + MKS WiFi V1.0+ESP3D it works perfectly. The USB port is damaged in my SKR V1. 3, and this configuration helped me very well.

**Comment by luc-github** [comment]
@Uz45 Ok thank you so pins are MKS wifi module one, good to know

**Comment by Uz45** [comment]
I used the original MKS WiFi V1. 0 module inserted normally into the wifi connector of the MKS TFT 32 V4.0 Board. 
ESP 3D-2.1 firmware was loaded into the WiFi module. I uploaded the firmware renaming esp3d.iso.bin to mkswifi.bin and used the MKS loader . After that I replaced the MKS TFT firmware with this one https://github.com/darkspr1te/MKSTFT_Marlin_Touch, without changing any UART-related settings in it. Then everything is normal for ESP 3D.

I use a simple non-original bootloader to load MKSTFT_Marlin_Touch into MKS TFT32 without using STLink. These are the only changes I've made. Unfortunately the original MKS TFT bootloader freezes after loading MKSTFT_Marlin_Touch. I don't know how to fix it yet.

**Comment by ETE-Design** [comment]
@Uz45 So you can use any options on ESP3D and they seems to Work, cause Luc had some problems getting Them to work... Also how to flash the MKSTFT_Marlin_Touch with non-original bootloader?

**Comment by Uz45** [comment]
Yes, everything works that I need, if something specific needs to be checked, I will check. Once ESP3D disappeared from the network and needed to flash the WIFI module again. There may be a problem with DHCP on my local network, I am currently using a static IP address. The bootloader I used from here https://github.com/Uz45/MKS-TFT/tree/master, pre-configuring it for yourself. Bootloader requires STLink_2. 0 to load in MKS TFT. This is a light version of the bootloader, it does not support downloading pictures. But it allows you to change the firmware without disassembling the printer and STLink. 

PS Sorry for my poor English, I use online translator.
![scresp3d](https://user-images.githubusercontent.com/48329159/72248247-86fc0600-3618-11ea-96ab-610e094ce6e8.jpg)
![QQscr](https://user-images.githubusercontent.com/48329159/72248256-8e231400-3618-11ea-8e93-7cf60a7a5033.jpg)

**Comment by ETE-Design** [comment]
@Uz45 Waht need to be pre-configured? And can you mabye make a "How To" For the bootloader part?
Do you know what it require in the bootloader to add the download pictures part?

**Comment by darkspr1te** [comment]
i am currently working on a lite and full bootloader for the mks28tft, will post source soon. based off libcm3 bootloader

**Comment by darkspr1te** [comment]
> I used the original MKS WiFi V1. 0 module inserted normally into the wifi connector of the MKS TFT 32 V4.0 Board.
> ESP 3D-2.1 firmware was loaded into the WiFi module. I uploaded the firmware renaming esp3d.iso.bin to mkswifi.bin and used the MKS loader . After that I replaced the MKS TFT firmware with this one https://github.com/darkspr1te/MKSTFT_Marlin_Touch, without changing any UART-related settings in it. Then everything is normal for ESP 3D.
> 
> I use a simple non-original bootloader to load MKSTFT_Marlin_Touch into MKS TFT32 without using STLink. These are the only changes I've made. Unfortunately the original MKS TFT bootloader freezes after loading MKSTFT_Marlin_Touch. I don't know how to fix it yet.

Booting using MKS bootloader fixed in latest commit, edit platformio.ini to switch between bootloader/no bootloader (for devs ease of use)

**Comment by darkspr1te** [comment]
New feature, Stm bootloader just like mama used to make ,
will compile and boot both factory and modded marlin firmware, just set you correct vector ,
https://github.com/darkspr1te/stm32f107vc_sd_bootloader, 
compiles in platformio.
