### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by Blueforcer** [darkspr1te/MKSTFT_Marlin_Touch#6]
Hey,

i found your git from https://github.com/makerbase-mks/MKS-TFT/issues/342
i have a mks tft 28 and marlin 2.0.1 on my Artillery Genius.
Am I right in assuming that your firmware works for this?
Because if I follow your instructions and copy the compiled bin with the tft folder to the sd card, the TFT will not find an update. Did I miss something? would be great if you could tell me.

**Comment by darkspr1te** [comment]
did you rename the update file mkstft28.bin do you have the v3.0 bootloader where it graphically shows you updating process ?

**Comment by Blueforcer** [comment]
If I rename it my tft starts the update but stops at 100% and don't go further.. After restart it only shows "booting".

While updating it shows 3.0.0 in the upper left corner, so I think it is the bootloader version?

**Comment by Uz45** [comment]
What version of TFT 28 do you have?

**Comment by Blueforcer** [comment]
Damn, just recognize it's a mks clone :-( maybe this doesn't work here?

**Comment by darkspr1te** [comment]
are you compiling using latest commit, only that only has bootloader patches in for using with mks bootloader. if possible post a pic somewhere and put url here, maybe we can patch it to work ?

**Comment by Blueforcer** [comment]
I used your precompiled one yesterday, I will compile it by myself later this evening and make some pictures!

**Comment by Blueforcer** [comment]
Here some Photos of the tft 
![image](https://user-images.githubusercontent.com/31169771/72669308-83111f00-3a30-11ea-98ec-fac399960896.png)
![image](https://user-images.githubusercontent.com/31169771/72669310-85737900-3a30-11ea-8945-737ca7f742bf.png)

**Comment by darkspr1te** [comment]
Thats different board to MKSTFT28 one , how ever it might be one of the other supported models, 
in platformio.ini file , comment out  default_envs = to  ;default_envs = 
This will build all versions, you will then find various bin files in .pio/build/TFT_VARIANT_NAME ,
copy each .bin file from the TFT_VARIANT_NAME/variantname.bin to a sdcard and try each one by naming it to mkstft28.bin (or which ever is the filename needed by your screen) , do you have actual working firmware bin file ? i can reverse engineer it's bootloader/firmware for it's start vectors as different devices have different ones (eg 0x6000 or 0x7000 for my screen)  and then create a profile for it.

**Comment by Blueforcer** [comment]
i will try all of them now. In the meantime i uploaded you the current firmware to my cloud:
http://cloud.blueforcer.de/s/DrA7AW2fRGYt8fA

**Comment by Blueforcer** [comment]
Well, **MKS_32_V1_4** is booting, starts to copy the fonts and pics, but says "No Printer attached". Maybe false Baudrate?
Found this one in the marlin firmware (ive also uploaded this one into the cloud):
![image](https://user-images.githubusercontent.com/31169771/72669856-1c433400-3a37-11ea-8908-46d2759d7a35.png)

But man.. this menu is awesome! Great Job!

**Comment by Blueforcer** [comment]
edit:
changed the baud rate to 250000 and it worked!

**Comment by darkspr1te** [comment]
Great to hear, can you clarify where you changed the baud rate (I'am assuming in marlin printer controller firmware ? or this Touch firmware ) 
and for others to note, this firmware was built for this tft board 
![mkstft28_board-v1-4](https://user-images.githubusercontent.com/3225653/72670024-25d19980-3a41-11ea-99b4-0a53d89b1f16.jpg)

**Comment by vzagranichnyy** [comment]
> Рад слышать, можете ли вы уточнить, где вы изменили скорость передачи данных (я полагаю, в прошивке контроллера принтера marlin? Или в этой прошивке Touch),
> и для других, чтобы заметить, эта прошивка была построена для этой платы TFT
> ![mkstft28_board-v1-4](https://user-images.githubusercontent.com/3225653/72670024-25d19980-3a41-11ea-99b4-0a53d89b1f16.jpg)

I can’t wait until it appears for v2.0

**Comment by Blueforcer** [comment]
> Great to hear, can you clarify where you changed the baud rate (I'am assuming in marlin printer controller firmware ? or this Touch firmware )
> and for others to note, this firmware was built for this tft board
> ![mkstft28_board-v1-4](https://user-images.githubusercontent.com/3225653/72670024-25d19980-3a41-11ea-99b4-0a53d89b1f16.jpg)

I changed it on the tft menu itself:)
Everything works now, get some unkown Gcode error while printing, but i think i can figure it out

**Comment by joskfg** [comment]
In Artillery X1 it builds and I can flash it, but it starts without icons. It doesn't write them. If I rename it to "mks_pic" the needed for the original firmware, it erase the pictures but it doesn't write the BMP.

EDIT: I need to learn to READ. The folder where I should put the bmps and fonts is KMS not root folder. Fixed, thanks.

**Comment by darkspr1te** [comment]
> In Artillery X1 it builds and I can flash it, but it starts without icons. It doesn't write them. If I rename it to "mks_pic" the needed for the original firmware, it erase the pictures but it doesn't write the BMP.
> 
> EDIT: I need to learn to READ. The folder where I should put the bmps and fonts is KMS not root folder. Fixed, thanks.

Folder for fonts/icons in this build is 0:root/MKS, in official (BTT build) it's 0:root/TFT28
